/*CREATE USER db_user WITH PASSWORD 'db_password';
CREATE DATABASE db OWNER db_user;
GRANT ALL PRIVILEGES ON DATABASE db TO db_user;
*/
CREATE USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow_db OWNER airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow;